export const XdcMainnet = {
    ID: 50,
    NAME: 'XDC (Mainnet)',
    NETWORK: 'XDC Mainmet',
    ICONURL: 'https://www.xinfin.org/assets/images/brand-assets/xinfin-xdc-network-logo.svg',
    ICON_BG: '#ffffff',
    NATIVECURRENCT_NAME: 'XDC',
    NATIVECURRENCT_SYMBOLS: 'XDC',
    NATIVECURRENCT_DECIMALS: 18,
    NATIVECURRENCT_RPCURL_DEFAULT: 'https://erpc.xinfin.network',
    NATIVECURRENCT_BLOCKEXPLORER_DEFAULT_NAME: 'XDC Blockchain Explorer',
    NATIVECURRENCT_BLOCKEXPLORER_DEFAULT_URL: 'https://explorer.xinfin.network/',
    TESTNET: false,
}

export const XdcTestNet = {
    ID: 51,
    NAME: 'Apothem',
    NETWORK: 'Apothem',
    ICONURL: 'https://www.xinfin.org/assets/images/brand-assets/xinfin-xdc-network-logo.svg',
    ICON_BG: '#fff',
    NATIVECURRENCT_NAME: 'XDC',
    NATIVECURRENCT_SYMBOLS: 'XDC',
    NATIVECURRENCT_DECIMALS: 18,
    NATIVECURRENCT_RPCURL_DEFAULT: 'https://erpc.apothem.network',
    NATIVECURRENCT_BLOCKEXPLORER_DEFAULT_NAME: 'Apothem Scanner',
    NATIVECURRENCT_BLOCKEXPLORER_DEFAULT_URL: 'https://explorer.apothem.network/',
    TESTNET: false,
}
export const Baklava = {
    ID: 62320,
    NAME: 'Celo (Baklava Testnet)',
    NETWORK: 'Celo (Baklava Testnet)',
    ICONURL: 'https://cryptologos.cc/logos/celo-celo-logo.svg?v=023',
    ICON_BG: '#0a0a0a',
    NATIVECURRENCT_NAME: 'CELO',
    NATIVECURRENCT_SYMBOLS: 'CELO',
    NATIVECURRENCT_DECIMALS: 18,
    NATIVECURRENCT_RPCURL_DEFAULT: 'https://baklava-forno.celo-testnet.org',
    NATIVECURRENCT_BLOCKEXPLORER_DEFAULT_NAME: 'Celo-Scanner',
    NATIVECURRENCT_BLOCKEXPLORER_DEFAULT_URL: 'https://baklava-blockscout.celo-testnet.org',
    TESTNET: false,
}